name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          cd custom_components/lmt_iot
          zip -r ../../lmt_iot.zip .
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: lmt_iot.zip
